# Generated by Django 4.2.30 on 2026-08-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_module', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('date', 'time'), name='unique_reservation_time'),
        ),
    ]
